export const SCHOOLYEAR_LIST_REQUEST = "SCHOOLYEAR_LIST_REQUEST"
export const SCHOOLYEAR_LIST_SUCCESS = "SCHOOLYEAR_LIST_SUCCESS"
export const SCHOOLYEAR_LIST_FAIL = "SCHOOLYEAR_LIST_FAIL"

export const SCHOOLYEAR_DETAIL_REQUEST = "SCHOOLYEAR_DETAIL_REQUEST"
export const SCHOOLYEAR_DETAIL_SUCCESS = "SCHOOLYEAR_DETAIL_SUCCESS"
export const SCHOOLYEAR_DETAIL_FAIL = "SCHOOLYEAR_DETAIL_FAIL"

export const SCHOOLYEAR_ADD_REQUEST = "SCHOOLYEAR_ADD_REQUEST"
export const SCHOOLYEAR_ADD_SUCCESS = "SCHOOLYEAR_ADD_SUCCESS"
export const SCHOOLYEAR_ADD_FAIL = "SCHOOLYEAR_ADD_FAIL"

export const SCHOOLYEAR_UPDATE_REQUEST = "SCHOOLYEAR_UPDATE_REQUEST"
export const SCHOOLYEAR_UPDATE_SUCCESS = "SCHOOLYEAR_UPDATE_SUCCESS"
export const SCHOOLYEAR_UPDATE_FAIL = "SCHOOLYEAR_UPDATE_FAIL"

export const SCHOOLYEAR_REMOVE_REQUEST = "SCHOOLYEAR_REMOVE_REQUEST"
export const SCHOOLYEAR_REMOVE_SUCCESS = "SCHOOLYEAR_REMOVE_SUCCESS"
export const SCHOOLYEAR_REMOVE_FAIL = "SCHOOLYEAR_REMOVE_FAIL"

export const CLASS_LIST_REQUEST = "CLASS_LIST_REQUEST"
export const CLASS_LIST_SUCCESS = "CLASS_LIST_SUCCESS"
export const CLASS_LIST_FAIL = "CLASS_LIST_FAIL"

export const CLASS_DETAIL_REQUEST = "CLASS_DETAIL_REQUEST"
export const CLASS_DETAIL_SUCCESS = "CLASS_DETAIL_SUCCESS"
export const CLASS_DETAIL_FAIL = "CLASS_DETAIL_FAIL"

export const CLASS_ADD_REQUEST = "CLASS_ADD_REQUEST"
export const CLASS_ADD_SUCCESS = "CLASS_ADD_SUCCESS"
export const CLASS_ADD_FAIL = "CLASS_ADD_FAIL"

export const CLASS_UPDATE_REQUEST = "CLASS_UPDATE_REQUEST"
export const CLASS_UPDATE_SUCCESS = "CLASS_UPDATE_SUCCESS"
export const CLASS_UPDATE_FAIL = "CLASS_UPDATE_FAIL"

export const CLASS_REMOVE_REQUEST = "CLASS_REMOVE_REQUEST"
export const CLASS_REMOVE_SUCCESS = "CLASS_REMOVE_SUCCESS"
export const CLASS_REMOVE_FAIL = "CLASS_REMOVE_FAIL"

export const PLANNEW_ADD_REQUEST = "PLANNEW_ADD_REQUEST"
export const PLANNEW_ADD_SUCCESS = "PLANNEW_ADD_SUCCESS"
export const PLANNEW_ADD_FAIL = "PLANNEW_ADD_FAIL"

export const PLANNEW_UPDATE_REQUEST = "PLANNEW_UPDATE_REQUEST"
export const PLANNEW_UPDATE_SUCCESS = "PLANNEW_UPDATE_SUCCESS"
export const PLANNEW_UPDATE_FAIL = "PLANNEW_UPDATE_FAIL"

export const PLANNEW_REMOVE_REQUEST = "PLANNEW_REMOVE_REQUEST"
export const PLANNEW_REMOVE_SUCCESS = "PLANNEW_REMOVE_SUCCESS"
export const PLANNEW_REMOVE_FAIL = "PLANNEW_REMOVE_FAIL"