export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST"
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS"
export const LOGIN_STUDENT_FAIL = "LOGIN_STUDENT_FAIL"

export const LOGOUT_STUDENT_REQUEST = "LOGOUT_STUDENT_REQUEST"
export const LOGOUT_STUDENT_SUCCESS = "LOGOUT_STUDENT_SUCCESS"
export const LOGOUT_STUDENT_FAIL = "LOGOUT_STUDENT_FAIL"

export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST"
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS"
export const LOGIN_TEACHER_FAIL = "LOGIN_TEACHER_FAIL"

export const LOGOUT_TEACHER_REQUEST = "LOGOUT_TEACHER_REQUEST"
export const LOGOUT_TEACHER_SUCCESS = "LOGOUT_TEACHER_SUCCESS"
export const LOGOUT_TEACHER_FAIL = "LOGOUT_TEACHER_FAIL"