export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST"
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_REQUEST"
export const LOGIN_STUDENT_FAIL = "LOGIN_STUDENT_REQUEST"

export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST"
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_REQUEST"
export const LOGIN_TEACHER_FAIL = "LOGIN_TEACHER_REQUEST"