export const PLANNEW_LIST_REQUEST = "PLANNEW_LIST_REQUEST"
export const PLANNEW_LIST_SUCCESS = "PLANNEW_LIST_SUCCESS"
export const PLANNEW_LIST_FAIL = "PLANNEW_LIST_FAIL"

export const PLANNEW_DETAIL_REQUEST = "PLANNEW_DETAIL_REQUEST"
export const PLANNEW_DETAIL_SUCCESS = "PLANNEW_DETAIL_SUCCESS"
export const PLANNEW_DETAIL_FAIL = "PLANNEW_DETAIL_FAIL"