export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST"
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS"
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL"

export const STUDENT_DETAIL_REQUEST = "STUDENT_DETAIL_REQUEST"
export const STUDENT_DETAIL_SUCCESS = "STUDENT_DETAIL_SUCCESS"
export const STUDENT_DETAIL_FAIL = "STUDENT_DETAIL_FAIL"

export const SCORE_LIST_REQUEST = "SCORE_LIST_REQUEST"
export const SCORE_LIST_SUCCESS = "SCORE_LIST_SUCCESS"
export const SCORE_LIST_FAIL = "SCORE_LIST_FAIL"

export const STUDENT_SCORE_REQUEST = "STUDENT_SCORE_REQUEST"
export const STUDENT_SCORE_SUCCESS = "STUDENT_SCORE_SUCCESS"
export const STUDENT_SCORE_FAIL = "STUDENT_SCORE_FAIL"