export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST"
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS"
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL"

export const STUDENT_LIST_CLASS_REQUEST = "STUDENT_LIST_CLASS_REQUEST"
export const STUDENT_LIST_CLASS_SUCCESS = "STUDENT_LIST_CLASS_SUCCESS"
export const STUDENT_LIST_CLASS_FAIL = "STUDENT_LIST_CLASS_FAIL"

export const STUDENT_DETAIL_REQUEST = "STUDENT_DETAIL_REQUEST"
export const STUDENT_DETAIL_SUCCESS = "STUDENT_DETAIL_SUCCESS"
export const STUDENT_DETAIL_FAIL = "STUDENT_DETAIL_FAIL"

export const SCORE_LIST_REQUEST = "SCORE_LIST_REQUEST"
export const SCORE_LIST_SUCCESS = "SCORE_LIST_SUCCESS"
export const SCORE_LIST_FAIL = "SCORE_LIST_FAIL"

export const ADD_SCORE_REQUEST = "ADD_SCORE_REQUEST"
export const ADD_SCORE_SUCCESS = "ADD_SCORE_SUCCESS"
export const ADD_SCORE_FAIL = "ADD_SCORE_FAIL"

export const UPDATE_SCORE_REQUEST = "UPDATE_SCORE_REQUEST"
export const UPDATE_SCORE_SUCCESS = "UPDATE_SCORE_SUCCESS"
export const UPDATE_SCORE_FAIL = "UPDATE_SCORE_FAIL"

export const STUDENT_SCORE_REQUEST = "STUDENT_SCORE_REQUEST"
export const STUDENT_SCORE_SUCCESS = "STUDENT_SCORE_SUCCESS"
export const STUDENT_SCORE_FAIL = "STUDENT_SCORE_FAIL"

export const REMOVE_STUDENT_REQUEST = "REMOVE_STUDENT_REQUEST"
export const REMOVE_STUDENT_SUCCESS = "REMOVE_STUDENT_SUCCESS"
export const REMOVE_STUDENT_FAIL = "REMOVE_STUDENT_FAIL"

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST"
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL"

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL"