export const ADD_TEACHER_REQUEST = "ADD_TEACHER_REQUEST"
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS"
export const ADD_TEACHER_FAIL = "ADD_TEACHER_FAIL"

export const TEACHER_LIST_REQUEST = "TEACHER_LIST_REQUEST"
export const TEACHER_LIST_SUCCESS = "TEACHER_LIST_SUCCESS"
export const TEACHER_LIST_FAIL = "TEACHER_LIST_FAIL"

export const TEACHER_DETAIL_REQUEST = "TEACHER_DETAIL_REQUEST"
export const TEACHER_DETAIL_SUCCESS = "TEACHER_DETAIL_SUCCESS"
export const TEACHER_DETAIL_FAIL = "TEACHER_DETAIL_FAIL"